config/routes.rb
Rails.application.routes.draw do
  constraints Constraints::TenantSubdomain.new do
    get '/', to: 'dashboard/home#index'
  end

  namespace :admin do
    get '/', to: 'panel#index', as: 'panel'
  end

  namespace :dashboard do
    get '/', to: 'home#index'

    resources :teams
    resources :customers
    resource :sessions, only: %i(new create destroy)
    resources :users, only: %i(index show new create destroy)
    resources :invites, module: :users, except: %i(show update edit)

    resources :projects, shallow: true do
      resources :tasks, module: :projects do
        patch :status, format: :ujs
      end
    end
  end

  resource :sign_up, only: %i(new create) do
    get :confirm
  end

  root 'home#index'
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_memberships
  has_many :members, through: :team_memberships, source: :user
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ::ApplicationController
  include Authenticable

  layout 'dashboard'

  authenticate :user

  helper_method :current_company

  rescue_from ActiveRecord::RecordNotFound do
    render status: :not_found
  end

  protected

  def current_tenant
    @current_tenant ||= Apartment::Tenant.current
  end

  def current_company
    @current_company ||= Company.find_by(subdomain: current_tenant)
  end

  def redirect_to_login
    redirect_to new_dashboard_sessions_url
  end
end

app/controllers/dashboard/customers_controller.rb
class Dashboard::CustomersController < Dashboard::BaseController
  before_action :set_customer, only: %i(destroy)
  before_action :set_customer_form, except: %i(index)

  def index
    @customers = Customer.all
  end

  def new; end

  def create
    if @customer_form.validate(params[:customer])
      @customer_form.save
    end

    respond_with @customer_form.sync, location: dashboard_customers_path
  end

  def edit; end

  def update
    if @customer_form.validate(params[:customer])
      @customer_form.save
    end

    respond_with @customer_form.sync, location: dashboard_customers_path
  end

  def destroy
    @customer.delete
    respond_with @customer, location: dashboard_customers_path
  end

  private

  def customer
    @customer ||= Customer.find_or_initialize_by(id: params[:id])
  end

  def set_customer_form
    @customer_form ||= CustomerForm.new(customer)
  end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < Dashboard::BaseController
  def index
  end
end

app/controllers/dashboard/projects/tasks_controller.rb
module Dashboard::Projects
  class TasksController < Dashboard::BaseController
    before_action :set_project, only: %i(new create)
    before_action :set_task_form

    def show
      @task = Project::Task.find(params[:id])
    end

    def new; end

    def create
      params[:project_task][:project_id] = @project.id

      if @task_form.validate(params[:project_task])
        @task_form.save
      end

      respond_with @task_form.sync, location: [:dashboard, @project]
    end

    def edit; end

    def update
      if @task_form.validate(params[:project_task])
        @task_form.save
      end

      respond_with @task_form.sync, location: [:dashboard, @task.project]
    end

    def status
      new_status = params[:status].to_i
      @task = Project::Task.find(params[:task_id])

      if @task && Project::Task.statuses.values.include?(new_status)
        @task.update_attribute(:status, new_status)
      end
    end

    private

    def task
      @task ||= Project::Task.find_or_initialize_by(id: params[:id])
    end

    def set_project
      @project ||= Project.find(params[:project_id])
    end

    def set_task_form
      @task_form ||= Project::TaskForm.new(task)
    end
  end
end

app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < Dashboard::BaseController
  before_action :set_project_form, except: %i(index)

  def index
    @projects = Project::Finder.all
  end

  def new; end

  def create
    @project_form = ProjectForm.new(Project.new)

    if @project_form.validate(params[:project])
      @project_form.save
    end

    respond_with @project_form.sync, location: dashboard_projects_path
  end

  def edit; end

  def update
    if @project_form.validate(params[:project])
      @project_form.save
    end

    respond_with @project_form.sync, location: dashboard_projects_path
  end

  private

  def project
    @project ||= Project.find_or_initialize_by(id: params[:id])
  end

  def set_project_form
    @project_form ||= ProjectForm.new(project)
  end
end

app/controllers/dashboard/sessions_controller.rb
class Dashboard::SessionsController < Dashboard::BaseController
  skip_before_action :require_resource!, only: %i(new create)

  layout 'session'

  def new
    @session = User::Session.new

    respond_with @session
  end

  def create
    @session = User::Session.new(session_params)
    @session.save

    respond_with @session, location: dashboard_path
  end

  def destroy
    current_user_session.destroy
    respond_with current_user_session, location: new_dashboard_sessions_path
  end

  private

  def flash_interpolation_options
    { user_name: current_user.name } if current_user.present?
  end

  def session_params
    params
      .require(:user_session)
      .permit(:email, :password)
  end
end

app/controllers/dashboard/teams_controller.rb
class Dashboard::TeamsController < Dashboard::BaseController
  def index
    @teams = Team.all.includes(:members)
  end

  def new
    @users = User.all
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    @team.team_memberships.build(members.map {|m| { user_id: m } })

    unless @team.save
      @users = User.all
    end

    respond_with @team, location: [:dashboard, :teams]
  end

  def edit
    @users = User.all
    @team = Team.find(params[:id])
  end

  def update
    @users = User.all
    @team = Team.find(params[:id])
    @team.members = User.find(members)

    @team.update_attributes(team_params)

    respond_with @team, location: [:dashboard, :teams]
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end

  def members
    (params[:team].require(:members) || []).reject(&:empty?)
  end
end

app/controllers/dashboard/users/invites_controller.rb
module Dashboard
  class Users::InvitesController < Dashboard::BaseController
    before_action :set_invite_form, only: %i(new create)

    def index
      @invites = User::Invite.pending
    end

    def new; end

    def create
      create_invite = Invite::Create.new

      create_invite.on(:success) do |invite|
        respond_with invite, location: dashboard_invites_path
      end

      create_invite.on(:error) do |form|
        respond_with form.sync
      end

      create_invite.call(@invite_form, current_company, params[:user_invite])
    end

    def destroy
      @invite = User::Invite.find(params[:id])
      @invite.destroy

      redirect_to dashboard_invites_path
    end

    private

    def set_invite_form
      @invite_form ||= User::InviteForm.new(User::Invite.new)
    end
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  skip_before_action :require_resource!, only: %i(new create)
  before_action :set_user, only: %i(show destroy)

  def index
    @users = User.all
  end

  def show; end

  def new
    user = User.new
    redeem_invite = RedeemInvite.new
    @user_form = UserForm.new(user)

    redeem_invite.on(:success) do |user|
      user = user
      render :new, layout: false
    end

    redeem_invite.on(:error) do
      render :new, layout: false
    end

    redeem_invite.call(params[:token])
  end

  def create
    create_user = User::Create.new

    create_user.on(:success) do
      redirect_to dashboard_url
    end

    create_user.on(:error) do
      flash[:alert] = 'Failed to create your account'
      redirect_to dashboard_url
    end

    create_user.call(params[:user])
  end

  def destroy
    @user.delete

    redirect_to dashboard_users_path
  end

  private

  def set_user
    @user ||= User.find(params[:id])
  end
end

app/views/dashboard/teams/_form.html.erb
<div class="form-row">
  <div class="form-column-one">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-input' %>
  </div>
</div>

<div class="form-row">
  <div class="form-column-one">
    <%= f.label :members, class: 'form-label' %>
    <%= f.select :members, options_from_collection_for_select(@users, :id, :name, f.object.members.pluck(:id)), {}, class: 'form-select', multiple: true, size: 10 %>
  </div>
</div>

app/views/dashboard/teams/_team.html.erb
<tr>
  <td><%= team.name %></td>
  <td><%= team.members.map(&:initials).join(' ') %></td>
  <td>
    <div class="dropdown">
      <%= link_to material_icon.more_vert, 'javascript:;', class: 'button-dropdown dropdown-action' %>

      <ul class="dropdown-content">
        <li><%= link_to "Editar", [:edit, :dashboard, team] %>
        <li><a href="#">Remover</a></li>
      </ul>
    </div>
  </td>
</tr>

app/views/dashboard/teams/edit.html.erb
<%= content_for :header_new_item do %>
  <%= nav_new_item(new_dashboard_team_path) %>
<% end %>

<div class="padding">
  <div class="box">
    <%= form_for [:dashboard, @team] do |f| %>
      <div class="form-content">
        <%= render 'form', f: f %>
      </div>

      <div class="form-action padding">
        <%= f.submit 'Salvar', class: 'button button-submit pull-right' %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/teams/index.html.erb
<%= content_for :header_new_item do %>
  <%= nav_new_item(new_dashboard_team_path) %>
<% end %>

<div class="padding">
  <div class="box">
    <table class="table padding">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Usuários</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% if @teams.empty? %>
          <tr>
            <td colspan="6">Nenhuma equipe cadastrada até o momento.</td>
          </tr>
        <% else %>
          <%= render @teams %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboard/teams/new.html.erb
<%= content_for :header_new_item do %>
  <%= nav_new_item(new_dashboard_team_path) %>
<% end %>

<div class="padding">
  <div class="box">
    <%= form_for [:dashboard, @team] do |f| %>
      <div class="form-content">
        <%= render 'form', f: f %>
      </div>

      <div class="form-action padding">
        <%= f.submit 'Criar', class: 'button button-submit pull-right' %>
      </div>
    <% end %>
  </div>
</div>