config/routes.rb
Rails.application.routes.draw do
  constraints Constraints::TenantSubdomain.new do
    get '/', to: 'dashboard/home#index'
  end

  namespace :admin do
    get '/', to: 'panel#index', as: 'panel'
  end

  namespace :dashboard do
    get '/', to: 'home#index'

    resources :teams
    resources :customers
    resource :sessions, only: %i(new create destroy)
    resources :users, only: %i(index show new create destroy)
    resources :invites, module: :users, except: %i(show update edit)

    resources :projects, shallow: true do
      resources :tasks, module: :projects do
        patch :status, format: :ujs
      end
    end
  end

  resource :sign_up, only: %i(new create) do
    get :confirm
  end

  root 'home#index'
end

app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  before_action :set_sign_up_form, only: %i(new create)

  def new; end

  def create
    sign_up = Company::SignUp.new

    sign_up.on(:success) { |company| redirect_to_dashboard(company) }
    sign_up.on(:error) do
      flash[:alert] = 'Failed to sign up company'
      render :new
    end

    sign_up.call(@sign_up_form, params[:sign_up])
  end

  def confirm
    confirm_sign_up = Company::ConfirmSignUp.new

    confirm_sign_up.subscribe(Tenant::Switch, on: :company_loaded, with: :call)

    confirm_sign_up.on(:success) do |company|
      redirect_to_dashboard(company, notice: 'Email confirmed')
    end

    confirm_sign_up.on(:error) do
      flash[:alert] = 'Failed to confirm your account'
      redirect_to root_path
    end

    confirm_sign_up.call(params[:company], params[:token])
  end

  private

  def company
    Company.new(owner: User.new)
  end

  def set_sign_up_form
    @sign_up_form ||= SignUpForm.new(company)
  end

  def redirect_to_dashboard(company, options = {})
    redirect_to dashboard_url(subdomain: company.subdomain), options
  end
end

app/views/sign_ups/new.html.erb
<h1>SignUp</h1>

<%= form_for @sign_up_form, url: sign_up_path do |f| %>
  <p><%= f.text_field :subdomain, placeholder: 'Domínio' %></p>
  <p><%= f.text_field :name, placeholder: 'Nome' %></p>

  <hr>

  <%= f.fields_for :owner do |of| %>
    <p><%= of.text_field :name, placeholder: 'Nome completo' %></p>
    <p><%= of.email_field :email, placeholder: 'Email' %></p>
    <p><%= of.password_field :password, placeholder: 'Senha' %></p>
    <p><%= of.password_field :password_confirmation, placeholder: 'Confirme a senha' %></p>
  <% end %>

  <p><%= f.submit 'Sign Up' %></p>
<% end %>