config/routes.rb
Rails.application.routes.draw do
  constraints Constraints::TenantSubdomain.new do
    get '/', to: 'dashboard/home#index'
  end

  namespace :admin do
    get '/', to: 'panel#index', as: 'panel'
  end

  namespace :dashboard do
    get '/', to: 'home#index'

    resources :teams
    resources :customers
    resource :sessions, only: %i(new create destroy)
    resources :users, only: %i(index show new create destroy)
    resources :invites, module: :users, except: %i(show update edit)

    resources :projects, shallow: true do
      resources :tasks, module: :projects do
        patch :status, format: :ujs
      end
    end
  end

  resource :sign_up, only: %i(new create) do
    get :confirm
  end

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :team_memberships
  has_many :teams, through: :team_memberships, source: :team
  has_many :projects, foreign_key: :responsible_id

  validates :name, :initials, presence: true
  validates :email, presence: true, uniqueness: true

  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::BCrypt
  end

  def confirmed!
    self[:confirmed] = true
  end
end

app/models/user/invite.rb
class User::Invite < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  scope :pending, -> { where(redeemed_at: nil) }

  def self.find_redeemable(invite_code)
    where(redeemed_at: nil, invite_code: invite_code).first
  end

  def pending?
    self[:redeemed_at].nil?
  end

  def invited?
    !!self[:invite_code] && !!self[:invited_at]
  end

  def invite!
    now = Time.current.utc
    self[:invite_code] = Digest::SHA1.hexdigest("--#{now}--#{self[:email]}--")
    self[:invited_at] = now
    save!
  end

  def redeemed!
    self[:redeemed_at] = Time.current.utc
    save!
  end

  def redeemed?
    self[:redeemed_at].present?
  end
end

app/models/user/session.rb
class User::Session < Authlogic::Session::Base
end

app/controllers/dashboard/users/invites_controller.rb
module Dashboard
  class Users::InvitesController < Dashboard::BaseController
    before_action :set_invite_form, only: %i(new create)

    def index
      @invites = User::Invite.pending
    end

    def new; end

    def create
      create_invite = Invite::Create.new

      create_invite.on(:success) do |invite|
        respond_with invite, location: dashboard_invites_path
      end

      create_invite.on(:error) do |form|
        respond_with form.sync
      end

      create_invite.call(@invite_form, current_company, params[:user_invite])
    end

    def destroy
      @invite = User::Invite.find(params[:id])
      @invite.destroy

      redirect_to dashboard_invites_path
    end

    private

    def set_invite_form
      @invite_form ||= User::InviteForm.new(User::Invite.new)
    end
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  skip_before_action :require_resource!, only: %i(new create)
  before_action :set_user, only: %i(show destroy)

  def index
    @users = User.all
  end

  def show; end

  def new
    user = User.new
    redeem_invite = RedeemInvite.new
    @user_form = UserForm.new(user)

    redeem_invite.on(:success) do |user|
      user = user
      render :new, layout: false
    end

    redeem_invite.on(:error) do
      render :new, layout: false
    end

    redeem_invite.call(params[:token])
  end

  def create
    create_user = User::Create.new

    create_user.on(:success) do
      redirect_to dashboard_url
    end

    create_user.on(:error) do
      flash[:alert] = 'Failed to create your account'
      redirect_to dashboard_url
    end

    create_user.call(params[:user])
  end

  def destroy
    @user.delete

    redirect_to dashboard_users_path
  end

  private

  def set_user
    @user ||= User.find(params[:id])
  end
end

app/views/dashboard/users/invites/_form.html.erb
<div class="form-row">
  <div class="form-column-two">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-input' %>
  </div>

  <div class="form-column-two">
    <%= f.label :email, class: 'form-label' %>
    <%= f.email_field :email, class: 'form-input' %>
  </div>
</div>

app/views/dashboard/users/invites/index.html.erb
<%= content_for :header_new_item do %>
  <%= nav_new_item(new_dashboard_invite_path) %>
<% end %>

<div class="padding">
  <div class="box">
    <% if @invites.empty? %>
      <p class="padding text-default text-center">Nenhum convite cadastrado. Cadastre um convite <%= link_to 'aqui', new_dashboard_invite_path %>.</p>
    <% else %>
      <table class="table padding">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Criado em</th>
          </tr>
        </thead>

        <tbody>
          <% @invites.each do |invite| %>
            <tr>
              <td><%= invite.name %></td>
              <td><%= invite.email %></td>
              <td><%= l invite.created_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/dashboard/users/invites/new.html.erb
<div class="padding">
  <div class="box">
    <%= form_for @invite_form, url: dashboard_invites_path do |f| %>
      <div class="form-content">
        <%= render 'form', f: f %>
      </div>

      <div class="form-action padding">
        <%= f.submit 'Enviar convite', class: 'button button-submit pull-right' %>
      </div>
    <% end %>
  </div>
</div>