config/routes.rb
Rails.application.routes.draw do
  constraints Constraints::TenantSubdomain.new do
    get '/', to: 'dashboard/home#index'
  end

  namespace :admin do
    get '/', to: 'panel#index', as: 'panel'
  end

  namespace :dashboard do
    get '/', to: 'home#index'

    resources :teams
    resources :customers
    resource :sessions, only: %i(new create destroy)
    resources :users, only: %i(index show new create destroy)
    resources :invites, module: :users, except: %i(show update edit)

    resources :projects, shallow: true do
      resources :tasks, module: :projects do
        patch :status, format: :ujs
      end
    end
  end

  resource :sign_up, only: %i(new create) do
    get :confirm
  end

  root 'home#index'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :customer
  belongs_to :responsible, polymorphic: true

  has_many :tasks, dependent: :delete_all

  def progress
    total = tasks.count
    return 0 if total == 0
    completed = tasks.finished.count
    (completed * 100) / total
  end

  def global_responsible
    self.responsible.to_global_id if responsible.present?
  end

  def global_responsible=(responsible)
    self.responsible = GlobalID::Locator.locate responsible
  end
end

app/models/project/task.rb
class Project::Task < ApplicationRecord
  enum status: { not_started: 0, started: 1, finished: 2 }

  belongs_to :project
  belongs_to :responsible, class_name: 'User'

  def to_partial_path
    'projects/tasks/task'
  end
end

app/controllers/dashboard/projects/tasks_controller.rb
module Dashboard::Projects
  class TasksController < Dashboard::BaseController
    before_action :set_project, only: %i(new create)
    before_action :set_task_form

    def show
      @task = Project::Task.find(params[:id])
    end

    def new; end

    def create
      params[:project_task][:project_id] = @project.id

      if @task_form.validate(params[:project_task])
        @task_form.save
      end

      respond_with @task_form.sync, location: [:dashboard, @project]
    end

    def edit; end

    def update
      if @task_form.validate(params[:project_task])
        @task_form.save
      end

      respond_with @task_form.sync, location: [:dashboard, @task.project]
    end

    def status
      new_status = params[:status].to_i
      @task = Project::Task.find(params[:task_id])

      if @task && Project::Task.statuses.values.include?(new_status)
        @task.update_attribute(:status, new_status)
      end
    end

    private

    def task
      @task ||= Project::Task.find_or_initialize_by(id: params[:id])
    end

    def set_project
      @project ||= Project.find(params[:project_id])
    end

    def set_task_form
      @task_form ||= Project::TaskForm.new(task)
    end
  end
end

app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < Dashboard::BaseController
  before_action :set_project_form, except: %i(index)

  def index
    @projects = Project::Finder.all
  end

  def new; end

  def create
    @project_form = ProjectForm.new(Project.new)

    if @project_form.validate(params[:project])
      @project_form.save
    end

    respond_with @project_form.sync, location: dashboard_projects_path
  end

  def edit; end

  def update
    if @project_form.validate(params[:project])
      @project_form.save
    end

    respond_with @project_form.sync, location: dashboard_projects_path
  end

  private

  def project
    @project ||= Project.find_or_initialize_by(id: params[:id])
  end

  def set_project_form
    @project_form ||= ProjectForm.new(project)
  end
end

app/helpers/project_helper.rb
module ProjectHelper
  def project_progress(project)
    content_tag :div, class: 'progress progress-xxs' do
      content_tag :div, '', class: 'progress-bar success', style: "width: #{project.progress}%"
    end
  end
end

app/views/dashboard/projects/tasks/_details.html.erb
<div class="box">
  <div class="box-header">
    <h3><%= @task.title %></h3>
    <small>Criada <%= l @task.created_at, format: :short %></small>
  </div>

  <div class="box-tool">
    <%= select_tag :status,
                   options_for_select(
                     Project::Task.statuses_i18n.map { |k, v| [v, Project::Task.statuses[k]] },
                     @task.status_before_type_cast
                   ),
                   data: {
                     remote: true,
                     method: :PATCH,
                     url: dashboard_task_status_url(@task),
                   },
                   class: 'form-select' %>
  </div>

  <div class="box-body">
    <div>
      <strong>Responsável</strong>
      <p><%= @task.responsible.name %></p>
    </div>

    <div>
      <strong>Data desejada</strong>
      <p><%= 'Não especificado' %></p>
    </div>

    <div>
      <strong>Descrição</strong>
      <p><%= @task.description %></p>
    </div>
  </div>
</div>

app/views/dashboard/projects/tasks/_form.html.erb
<div class="form-row">
  <div class="form-column-two">
    <%= f.label :title, class: 'form-label' %>
    <%= f.text_field :title, class: 'form-input' %>
  </div>

  <div class="form-column-two">
    <%= f.label :responsible_id, class: 'form-label' %>
    <%= f.select :responsible_id, options_from_collection_for_select(User.all, :id, :name), {}, class: 'form-select' %>
  </div>

  <div class="form-column-one">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_area :description, class: 'form-textarea' %>
  </div>
</div>

app/views/dashboard/projects/tasks/_new.html.erb
<%= form_for [:dashboard, @task_form] do |f| %>
  <%= f.hidden_field :project_id %>

  <div class="form-content">
    <%= render 'form', f: f %>
  </div>

  <div class="form-action padding">
    <%= f.submit 'Salvar', class: 'button button-submit pull-right' %>
  </div>
<% end %>

app/views/dashboard/projects/tasks/_task.html.erb
<tr id="task-<%= task.id %>">
  <td><%= task.id %></td>
  <td><%= link_to task.title, dashboard_task_path(task), remote: true, class: 'task-modal' %></td>
  <td><%= task.status_i18n %></td>
  <td><%= task.responsible.try :name %></td>
  <td><%= '' %></td>
  <td><%= task.deadline %></td>
  <td>
    <div class="dropdown">
      <%= link_to material_icon.more_vert, 'javascript:;', class: 'button-dropdown dropdown-action' %>

      <ul class="dropdown-content">
        <li><%= link_to "Editar", edit_dashboard_task_path(task) %>
        <li><a href="#">Remover</a></li>
      </ul>
    </div>
  </td>
</tr>

app/views/dashboard/projects/tasks/edit.html.erb
<div class="padding">
  <div class="box">
    <%= form_for @task_form, url: dashboard_task_path(@task_form), method: :PUT do |f| %>
      <div class="form-content">
        <%= render 'form', f: f %>
      </div>

      <div class="form-action padding">
        <%= f.submit 'Editar', class: 'button button-submit pull-right' %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/projects/tasks/new.html.erb
<div class="padding">
  <div class="box">
    <%= form_for [:dashboard, @task_form] do |f| %>
      <%= f.hidden_field :project_id %>

      <div class="form-content">
        <%= render 'form', f: f %>
      </div>

      <div class="form-action padding">
        <%= f.submit 'Salvar', class: 'button button-submit pull-right' %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/projects/tasks/new.js.erb
console.log('aqui');
$('#new-task-modal .modal__content').html("<%= j render('new') %>");
$('#new-task-modal').iziModal('open');

app/views/dashboard/projects/tasks/show.js.erb
$('#task-modal .modal__content').html("<%= j render('details') %>");
$('#task-modal').iziModal('setTitle', 'Exibindo tarefa #<%= @task.id %>');
$('#task-modal').iziModal('open');

app/views/dashboard/projects/tasks/status.js.erb
$("#task-<%= @task.id %>").replaceWith("<%= j render('dashboard/projects/tasks/task', task: @task) %>");